// tslint:disable

export const Roles = [{
  "roleId": 1,
  "name": "Administrator"
},
{
  "roleId": 2,
  "name": "User"
},
{
  "roleId": 3,
  "name": "Mobile User"
},
{
  "roleId": 4,
  "name": "Project manager"
}]

export const RoleClaimValues = [{
  "roleClaimValueId": 1,
  "roleId": 1,
  "roleClaimId": 1
},
{
  "roleClaimValueId": 2,
  "roleId": 1,
  "roleClaimId": 2
},
{
  "roleClaimValueId": 2,
  "roleId": 1,
  "roleClaimId": 3
}]

export const Users = [{
    "id": 1,
    "firstName": "Saunders",
    "lastName": "Fairn",
    "email": "sfairn0@pbs.org",
    "birthday": "10/08/1997"
  }, {
    "id": 2,
    "firstName": "Deina",
    "lastName": "Rubinsohn",
    "email": "drubinsohn1@gov.uk",
    "birthday": "11/12/1984"
  }, {
    "id": 3,
    "firstName": "Sher",
    "lastName": "Blincoe",
    "email": "sblincoe2@etsy.com",
    "birthday": "23/12/1981"
  }, {
    "id": 4,
    "firstName": "Alley",
    "lastName": "Munden",
    "email": "amunden3@wikimedia.org",
    "birthday": "05/07/1998"
  }, {
    "id": 5,
    "firstName": "Portie",
    "lastName": "Landers",
    "email": "planders4@google.es",
    "birthday": "16/06/1996"
  }, {
    "id": 6,
    "firstName": "Noach",
    "lastName": "Cronchey",
    "email": "ncronchey5@cloudflare.com",
    "birthday": "19/06/1992"
  }, {
    "id": 7,
    "firstName": "Abraham",
    "lastName": "Barstowk",
    "email": "abarstowk6@yandex.ru",
    "birthday": "05/10/1999"
  }, {
    "id": 8,
    "firstName": "Tiffany",
    "lastName": "Hedin",
    "email": "thedin7@360.cn",
    "birthday": "24/02/1993"
  }, {
    "id": 9,
    "firstName": "Eugenio",
    "lastName": "Hacker",
    "email": "ehacker8@google.cn",
    "birthday": "02/08/1997"
  }, {
    "id": 10,
    "firstName": "Reube",
    "lastName": "Zellmer",
    "email": "rzellmer9@hugedomains.com",
    "birthday": "31/08/1997"
  }, {
    "id": 11,
    "firstName": "Cordey",
    "lastName": "Leacy",
    "email": "cleacya@patch.com",
    "birthday": "01/02/1991"
  }, {
    "id": 12,
    "firstName": "Mella",
    "lastName": "Breward",
    "email": "mbrewardb@state.tx.us",
    "birthday": "21/06/1982"
  }, {
    "id": 13,
    "firstName": "Janette",
    "lastName": "Scotchmur",
    "email": "jscotchmurc@networkadvertising.org",
    "birthday": "21/12/1991"
  }, {
    "id": 14,
    "firstName": "Meade",
    "lastName": "Cote",
    "email": "mcoted@myspace.com",
    "birthday": "28/12/1983"
  }, {
    "id": 15,
    "firstName": "Elena",
    "lastName": "Dominichelli",
    "email": "edominichellie@hostgator.com",
    "birthday": "19/09/1997"
  }, {
    "id": 16,
    "firstName": "Millicent",
    "lastName": "Uff",
    "email": "mufff@redcross.org",
    "birthday": "01/12/1986"
  }, {
    "id": 17,
    "firstName": "Coralyn",
    "lastName": "Lensch",
    "email": "clenschg@wisc.edu",
    "birthday": "16/12/1998"
  }, {
    "id": 18,
    "firstName": "Egor",
    "lastName": "Coslett",
    "email": "ecosletth@usda.gov",
    "birthday": "30/06/1998"
  }, {
    "id": 19,
    "firstName": "Abrahan",
    "lastName": "Jelkes",
    "email": "ajelkesi@naver.com",
    "birthday": "09/05/1997"
  }, {
    "id": 20,
    "firstName": "Virginia",
    "lastName": "Fishlee",
    "email": "vfishleej@mozilla.org",
    "birthday": "17/06/1997"
  }, {
    "id": 21,
    "firstName": "Rebe",
    "lastName": "Hotchkin",
    "email": "rhotchkink@usa.gov",
    "birthday": "31/05/1987"
  }, {
    "id": 22,
    "firstName": "Dag",
    "lastName": "Mandel",
    "email": "dmandell@google.com.hk",
    "birthday": "18/12/1995"
  }, {
    "id": 23,
    "firstName": "Ruthann",
    "lastName": "Stronack",
    "email": "rstronackm@jiathis.com",
    "birthday": "09/05/1985"
  }, {
    "id": 24,
    "firstName": "Kristan",
    "lastName": "Lotte",
    "email": "klotten@issuu.com",
    "birthday": "18/10/1990"
  }, {
    "id": 25,
    "firstName": "Harrietta",
    "lastName": "Tinklin",
    "email": "htinklino@google.es",
    "birthday": "12/09/1984"
  }, {
    "id": 26,
    "firstName": "Adela",
    "lastName": "Pawfoot",
    "email": "apawfootp@google.it",
    "birthday": "25/09/1991"
  }, {
    "id": 27,
    "firstName": "Shellysheldon",
    "lastName": "Garretson",
    "email": "sgarretsonq@nationalgeographic.com",
    "birthday": "28/12/1999"
  }, {
    "id": 28,
    "firstName": "Bev",
    "lastName": "Mistry",
    "email": "bmistryr@tiny.cc",
    "birthday": "04/05/1984"
  }, {
    "id": 29,
    "firstName": "Luce",
    "lastName": "McKleod",
    "email": "lmckleods@studiopress.com",
    "birthday": "16/11/1982"
  }, {
    "id": 30,
    "firstName": "Tara",
    "lastName": "Epelett",
    "email": "tepelettt@homestead.com",
    "birthday": "05/09/1991"
  }, {
    "id": 31,
    "firstName": "Teodoor",
    "lastName": "Trude",
    "email": "ttrudeu@go.com",
    "birthday": "14/09/1989"
  }, {
    "id": 32,
    "firstName": "Michale",
    "lastName": "MacCafferty",
    "email": "mmaccaffertyv@exblog.jp",
    "birthday": "25/09/1999"
  }, {
    "id": 33,
    "firstName": "Thedric",
    "lastName": "Ogilvy",
    "email": "togilvyw@prnewswire.com",
    "birthday": "25/06/1987"
  }, {
    "id": 34,
    "firstName": "Paulina",
    "lastName": "McHugh",
    "email": "pmchughx@unblog.fr",
    "birthday": "26/03/1994"
  }, {
    "id": 35,
    "firstName": "Cletus",
    "lastName": "Thew",
    "email": "cthewy@t-online.de",
    "birthday": "09/04/1993"
  }, {
    "id": 36,
    "firstName": "Tobit",
    "lastName": "Claussen",
    "email": "tclaussenz@si.edu",
    "birthday": "20/09/1988"
  }, {
    "id": 37,
    "firstName": "Nady",
    "lastName": "Brisco",
    "email": "nbrisco10@loc.gov",
    "birthday": "17/02/1997"
  }, {
    "id": 38,
    "firstName": "Lance",
    "lastName": "Gumme",
    "email": "lgumme11@europa.eu",
    "birthday": "15/09/1981"
  }, {
    "id": 39,
    "firstName": "Kaia",
    "lastName": "Truder",
    "email": "ktruder12@geocities.com",
    "birthday": "03/02/1999"
  }, {
    "id": 40,
    "firstName": "Rawley",
    "lastName": "Meagh",
    "email": "rmeagh13@nhs.uk",
    "birthday": "02/03/1991"
  }, {
    "id": 41,
    "firstName": "Felicio",
    "lastName": "Gommowe",
    "email": "fgommowe14@wired.com",
    "birthday": "14/06/1993"
  }, {
    "id": 42,
    "firstName": "Sharla",
    "lastName": "Hanson",
    "email": "shanson15@ask.com",
    "birthday": "26/10/1986"
  }, {
    "id": 43,
    "firstName": "Hendrik",
    "lastName": "Corck",
    "email": "hcorck16@fastcompany.com",
    "birthday": "30/05/1996"
  }, {
    "id": 44,
    "firstName": "Goldia",
    "lastName": "Danes",
    "email": "gdanes17@uiuc.edu",
    "birthday": "08/02/1989"
  }, {
    "id": 45,
    "firstName": "Sharleen",
    "lastName": "Fardo",
    "email": "sfardo18@salon.com",
    "birthday": "10/02/1985"
  }, {
    "id": 46,
    "firstName": "Maury",
    "lastName": "Signe",
    "email": "msigne19@paginegialle.it",
    "birthday": "30/05/1990"
  }, {
    "id": 47,
    "firstName": "Farrah",
    "lastName": "Mead",
    "email": "fmead1a@mail.ru",
    "birthday": "04/09/1990"
  }, {
    "id": 48,
    "firstName": "Laetitia",
    "lastName": "Gulvin",
    "email": "lgulvin1b@ox.ac.uk",
    "birthday": "04/08/1994"
  }, {
    "id": 49,
    "firstName": "Herrick",
    "lastName": "Lethbury",
    "email": "hlethbury1c@ucla.edu",
    "birthday": "17/12/1980"
  }, {
    "id": 50,
    "firstName": "Renell",
    "lastName": "Lambarton",
    "email": "rlambarton1d@artisteer.com",
    "birthday": "08/04/1991"
  }, {
    "id": 51,
    "firstName": "Ingrim",
    "lastName": "Marages",
    "email": "imarages1e@craigslist.org",
    "birthday": "14/06/1994"
  }]